name: Build and Analyze
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-frontend:
    name: SonarQube Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run tests with coverage (Frontend)
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: SonarQube Scan (Frontend)
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ./frontend
          args: >
            -Dsonar.projectKey=Hassin007_ProdGradeNotesApp
            -Dsonar.organization=hassin007
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  sonarqube-backend:
    name: SonarQube Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run tests with coverage (Backend)
        working-directory: ./backend
        run: npm test -- --coverage

      - name: SonarQube Scan (Backend)
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ./backend
          args: >
            -Dsonar.projectKey=Hassin007_ProdGradeNotesApp
            -Dsonar.organization=hassin007
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
